# Generated by Django 4.2.2 on 2023-08-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_payments_payment_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('3_paid', 'paid'), ('1_cart', 'cart'), ('2_waiting_for_paymont', 'waiting_for_paymont')], default='1_cart', max_length=32),
        ),
    ]
