# Generated by Django 4.2.2 on 2023-08-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_payment_options_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1_cart', 'cart'), ('3_paid', 'paid'), ('2_waiting_for_paymont', 'waiting_for_paymont')], default='1_cart', max_length=32),
        ),
    ]
